---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
library(rvest)
a<-"https://www.ptt.cc/bbs/NBA/index.html"
b<-"https://www.ptt.cc/bbs/NBA/index4630.html"
c<-"https://www.ptt.cc/bbs/NBA/index4629.html"
d<-"https://www.ptt.cc/bbs/NBA/index4628.html"
e<-"https://www.ptt.cc/bbs/NBA/index4627.html"
f<-"https://www.ptt.cc/bbs/NBA/index4626.html"
vec<-c(a,b,c,d,e,f)
Total<-NULL
for(i in vec){
  NBAContent<-read_html(i)
post_title<-NBAContent %>%
html_nodes(".title") %>%
html_text()
post_PushNum<-NBAContent %>%
html_nodes(".nrec") %>%
html_text()
post_author<- NBAContent %>%
html_nodes(".author") %>%
html_text()
tempPage<- data.frame(title=post_title,PushNum=post_PushNum,
                          author=post_author)
  Total<-rbind(Total,tempPage)
  next
}
NBA_posts<-Total
#knitr::kable(NBA_posts[1:100,c("title","PushNum","author")])
```

## 爬蟲結果呈現
```{r}
knitr::kable(
  NBA_posts[1:100,c("title","PushNum","author")]) 
```

## 解釋爬蟲結果 
```{r}
str(NBA_posts)
```

用str()可以看到一共爬出109篇文章。

```{r}
table(NBA_posts$author)
```

用table()可以看到在NBA的ptt版上,有一位叫 Rambo的人很常發文,從上面的資料我們可以看到他總共發了26篇文章。

整體分析資料結果:
1.從爬出來的資料我們可看到在NBA這個版上的文章被噓的文章並不是很多,除非太過於主觀支持哪一方的文章才會被噓。
2.我們還可以看到只要[Live]文章每一篇都有人推,有些推文數還不少。
3.在讚爆的文章分類中我們可以看到在NBA[討論]文章中佔的比例比較多。
4.很多[Live]的文章都是Rambo這個使用者Po的。
